### ISSUE TITLE
Update documentation and dependencies to specify need for Ruby 2.0 or greater.

### ISSUE THREAD

**Issue by HotShot3150** [Shopify/money#100]
Recent changes breaks functionality with projects using > Ruby 2.0. Steps should be taken to update documentation and dependencies to inform developers of the requirements for using this gem.

**Comment by elfassy** [comment]
Hey @HotShot3150! Thanks for the feedback. We're making a push towards a v1.0. The requirement will be Ruby > 2.3 and Rails > 5.0. Cheers

**Comment by HotShot3150** [comment]
That sounds excellent! I was working on an older Ruby 1.9.3 project to bring it up to date and ran into the dependency issue while slowly versioning up the gems. Thanks for all you guys do!
