### ISSUE TITLE
uninitialized constant ActiveRecord::Type

### ISSUE THREAD

**Issue by HotShot3150** [Shopify/money#158]
Attempting to bundle this gem with an older Rails 3.2.19 application running on Ruby 2.1.10 I get the following error:
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'money'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant ActiveRecord::Type
Backtrace for gem load error is:
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/shopify-money-0.11.3/lib/money_column/active_record_type.rb:1:in `<top (required)>'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/shopify-money-0.11.3/lib/money_column.rb:2:in `require_relative'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/shopify-money-0.11.3/lib/money_column.rb:2:in `<top (required)>'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/shopify-money-0.11.3/lib/money.rb:10:in `require_relative'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/shopify-money-0.11.3/lib/money.rb:10:in `<top (required)>'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/riverbryant/projects/global-legacy/config/application.rb:7:in `<top (required)>'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/railties-3.2.19/lib/rails/commands.rb:53:in `require'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/railties-3.2.19/lib/rails/commands.rb:53:in `block in <top (required)>'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/railties-3.2.19/lib/rails/commands.rb:50:in `tap'
/Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/railties-3.2.19/lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
Bundler Error Backtrace:
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	from /Users/riverbryant/projects/global-legacy/config/application.rb:7:in `<top (required)>'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/railties-3.2.19/lib/rails/commands.rb:53:in `require'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/railties-3.2.19/lib/rails/commands.rb:53:in `block in <top (required)>'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/railties-3.2.19/lib/rails/commands.rb:50:in `tap'
	from /Users/riverbryant/.rvm/gems/ruby-2.1.10@global_legacy/gems/railties-3.2.19/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Gemfile**
source 'https://rubygems.org'

ruby "2.1.10"

gem 'rails', '3.2.19'
gem 'pg'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'execjs'
  gem 'uglifier', '>= 1.0.3'
end

gem 'airbrake'
gem 'animate-rails', '=1.0.2'
gem 'aws-s3', '~> 0.6.3'
gem 'aws-sdk', '~> 1.11.1'
gem 'awesome_print', '~> 1.6.1'
gem 'braintree', '~> 2.26.0'
gem 'cancan', '~> 1.6.10'
gem 'carmen', '~> 0.2.0'
gem 'devise', '~> 1.5.0'
gem 'escape_utils', "~> 1.2.1"
commented: gem "font-awesome-rails", "3.2.1.2"
gem 'friendly_id', '~> 4.0.9'
gem 'hominid', '~> 3.0.5'
gem 'jquery-rails', '~> 3.1.3'
gem 'kaminari', '~> 0.16.3'
gem 'koala', '~> 2.0.0'
gem 'geocoder', '~> 1.2.9'
gem 'memcache-client', '~> 1.8.5'
gem 'shopify-money', require: 'money'
gem 'omniauth-facebook', '~> 4.0.0'
gem 'paperclip', '~> 2.3'
gem 'paper_trail', '~> 2'
gem 'pg_search', '~> 1.0.4'
gem 'prawn', '~> 0.12.0' #prawn version 2 requires ruby 2
gem 'pusher', '~> 0.14.5'
gem 'rabl', '~> 0.11.6'
gem 'redcarpet', '= 1.17.2'
gem 'redis', '~> 3.2.1'
gem 'resque', '~> 1.25.2', :require => "resque/server"
gem 'rest-client', '~> 1.8.0' #, :git => "https://github.com/archiloque/rest-client.git"
gem 'sass', '3.2.12'
gem 'simple_form', '~> 2.1.2'
gem 'turnout', '~> 2.4.0'
gem 'validates_timeliness', '~> 3.0.13'
gem 'whenever', '~> 0.9.4' , :require => false
gem 'whenever-elasticbeanstalk'
gem 'rack', '= 1.4.7'
gem 'god'
commented: gem 'puma', '3.11.4'

group :development, :test do
  gem 'guard', '>= 2.1.0'
  gem 'rspec-rails', '~> 2.14.0' #not ready for rspec 3.3
  gem 'shoulda-matchers', '~> 2.4.0'
  gem "guard-rspec", '~> 4.0.3' #not ready for rspec 3.3
  gem "rb-fsevent"
  gem "guard-annotate"
  gem "guard-rails"
  gem "guard-livereload"
  gem 'railroady'
  gem 'thin', '1.7.2'
  gem 'zeus'
  gem "factory_girl_rails"
  gem "capybara"
  gem 'capybara-webkit', '~> 1.0.0'
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'delorean'
  gem 'json_spec', '~> 1.0.0' #not ready for rspec 3.3
  gem 'mocha', :require => false
end

group :test do
  gem 'vcr', '~> 2.6.0'
  gem 'webmock'
end

group :development do
  gem 'capistrano', '2.15.5'
  gem 'capistrano-ext'
  gem 'rails3-generators'
  gem 'annotate'
  gem 'libnotify', :require => false
  gem 'rb-inotify', :require => false
  gem 'mail_safe', :require => false
  gem 'better_errors', '~> 1.0.1' #better errors 2.0 requires ruby 2.0
  gem 'binding_of_caller'
end

Any insights into how I can resolve this issue?

**Comment by HotShot3150** [comment]
It appears the error was being generated from the require 'money' portion of the line. Looking further into this aspect of the error.

**Comment by elfassy** [comment]
Unfortunately `Rails 3.2.19` is no longer supported.
