### ISSUE TITLE
Currency rounding conventions

### ISSUE THREAD

**Issue by bdewater** [Shopify/money#161]
TIL: JPY is traditionally rounded down when calculating e.g. taxes. We default via BigDecimal to 'half up'. We should add this to our currency database.

**Comment by SippyGirl** [comment]
Any updates on this issue? The merchant contacted support on June 13 and we haven't been able to explain the issue.

**Comment by bdewater** [comment]
Closing this as it's not related to how the gem rounds - but how the application decides to carry precision forward or round tax lines individually.
