### ISSUE TITLE
Needs to correctly handle internationalization

### ISSUE THREAD

**Issue by csaunders** [Shopify/money#2]
Money makes an assumption about the "localization" and tries to do everything at once.

For example, if I'm an Anglo in Canada/US I'd expect `Money.new('10.123').should == Money.new(10.12)`  whereas if I'm German I'd expect `Money.new('10.123').should == Money.new(10123.00)`

What we may want to start doing is adding support for various culture codes (or perhaps currency) when it comes to extracting these numbers into their "proper" format.

**Comment by elfassy** [comment]
String to money will be handled by the parser, see https://github.com/Shopify/money/pull/125
