### ISSUE TITLE
Money#parse returns wrong result for input with 3 decimal digits

### ISSUE THREAD

**Issue by kajol-maheshwari** [Shopify/money#215]
Currently, when we pass input with 3 decimal digits to the `parse` method, it returns an invalid input:
```ruby
price = Money.parse("70.415") # => returns 70415
```
I can see [here](https://github.com/Shopify/money/blob/master/lib/money/money_parser.rb#L149) that we are normalising the input based on minor units for the given currency(which defaults to `XXX` in the above example and have `minor_units = 2`) which returns wrong result in our case.
We are using this method in Shop backend [here](https://github.com/Shopify/arrive-server/blob/633e28aca6a6c21659c5478935759035bddac25a/app/services/email_parsing/email_data_schema_parser.rb#L114) to parse the price value we receive from buyer's online shopping data and it's very common for us to have 3 decimal digits for price and hence we cannot rely on currency's minor units as in the code.
Issue reported by user: https://github.com/Shopify/email-parser/issues/1393

**Comment by kajol-maheshwari** [comment]
Closing this, after discussion with the team we realised this can be an expected behaviour from the gem and can be handled at our end.

**Comment by Sapphire64** [comment]
To clarify, we were getting an amount like `10.95` and then dividing it by quantity, giving us `5.475` back. I tested on Python lib we use https://github.com/scrapinghub/price-parser and the behaviour was similar.
