### ISSUE TITLE
`Money#from_cents` does not take into account non-decimal currencies

### ISSUE THREAD

**Issue by dominiquefl** [Shopify/money#220]
`Money#from_cents` does not take into account non-decimal currencies prior to creating the money object. The resulting object for non-decimal currencies (such as JPY) will then have a monetary value 1/100 of the actual amount.

https://github.com/Shopify/money/blob/52c160446e0451d410c781f809fa9e1b3523fd6b/lib/money/money.rb#L38-L40

**Comment by bdewater** [comment]
That's correct, this is legacy behaviour from when this gem didn't have currency at all. Use `from_subunits` instead :)

**Comment by dominiquefl** [comment]
Thanks! `from_subunits` is what we need.
