### ISSUE TITLE
Two money objects are equal when value are the same but one of the currency is NullCurrency

### ISSUE THREAD

**Issue by wendy-shopify** [Shopify/money#245]
When trying to do equality, two following objects will actually be equal
```
money_1 = Money.new(10, "USD")
money_2 = Money.new(10)

> money_1 == money_2
=> true
```

I found the reason is due to checking [`currency.compatible?`](https://github.com/Shopify/money/blob/a5dc4902a78a1d3be66065ae560e5f71b4fd6d53/lib/money/money.rb#L166) then [`currency.eql?`](https://github.com/Shopify/money/blob/a5dc4902a78a1d3be66065ae560e5f71b4fd6d53/lib/money/currency.rb#L49-L51) when implementing `money.eql?`

**Comment by elfassy** [comment]
this is expected behaviour, the null currency is compatible with all other currencies. If you don't want this behaviour make sure you didn't opt in using `config.legacy_default_currency!` (if you still want to use a default currency, set it explicitly `config.default_currency = "USD"`
